### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by SpaghettiToastBook** [henriquegemignani/py-nod#1]
Maybe I'm doing something stupid, but I can't seem to install this due to compilation errors:
```
$ pip install --user nod
Collecting nod
  Using cached https://files.pythonhosted.org/packages/cf/f4/ead8bdf804fee74c75bc895ae77592b6c9431a31cd35381ff8faf6adf11c/nod-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-vyt09y6o/nod/_nod.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/ExtractionContext.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/createProgressCallbackFunction.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/DiscBase.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/string_view.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/OpenDiscFromImage.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/SystemStringView.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/SystemUTF8Conv.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/SystemString.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/SystemStringConv.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/DiscBuilderGCN.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/createFProgressFunction.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/EBuildResult.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/EBuildResult_Success.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/EBuildResult_Failed.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/EBuildResult_DiskFull.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/string_to_system_string.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/registerLogvisorToExceptionConverter.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/removeLogvisorToExceptionConverter.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/_handleNativeException.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import cython
    from libcpp cimport bool as c_bool
    from libcpp.string cimport string
    from libcpp.memory cimport unique_ptr
    
    from nod_wrap cimport ExtractionContext as c_ExtractionContext, \
    ^
    ------------------------------------------------------------
    
    _nod.pyx:10:0: 'nod_wrap/checkException.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        OpenDiscFromImage, SystemStringView, SystemUTF8Conv, SystemString, SystemStringConv, \
        DiscBuilderGCN as c_DiscBuilderGCN, createFProgressFunction, EBuildResult,\
        EBuildResult_Success, EBuildResult_Failed, EBuildResult_DiskFull, string_to_system_string, \
        registerLogvisorToExceptionConverter, removeLogvisorToExceptionConverter, _handleNativeException, checkException
    
    cdef SystemString _str_to_system_string(str path):
        ^
    ------------------------------------------------------------
    
    _nod.pyx:18:5: 'SystemString' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        registerLogvisorToExceptionConverter()
        yield
        removeLogvisorToExceptionConverter()
    
    cdef class ExtractionContext:
        cdef c_ExtractionContext c_context
            ^
    ------------------------------------------------------------
    
    _nod.pyx:36:9: 'c_ExtractionContext' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def set_progress_callback(self, callback):
            self.c_context.progressCB = createProgressCallbackFunction(callback, invoke_callback_function)
    
    cdef class Partition:
        cdef c_DiscBase.IPartition*c_partition
            ^
    ------------------------------------------------------------
    
    _nod.pyx:53:9: 'IPartition' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class Partition:
        cdef c_DiscBase.IPartition*c_partition
    
        @staticmethod
        cdef create(c_DiscBase.IPartition* c_partition):
                   ^
    ------------------------------------------------------------
    
    _nod.pyx:56:16: 'IPartition' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                if not extraction_successful:
                    raise RuntimeError("Unable to extract")
            return _handleNativeException(work)
    
    cdef class DiscBase:
        cdef unique_ptr[c_DiscBase] c_disc
                                 ^
    ------------------------------------------------------------
    
    _nod.pyx:74:30: unknown type in template argument
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            else:
                return None
    
    
    cdef class DiscBuilderGCN:
        cdef c_DiscBuilderGCN* c_builder
            ^
    ------------------------------------------------------------
    
    _nod.pyx:85:9: 'c_DiscBuilderGCN' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            partition.c_partition = c_partition
            return partition
    
        def extract_to_directory(self, path: str, context: ExtractionContext) -> None:
            def work():
                cdef SystemString system_string = _str_to_system_string(path)
                    ^
    ------------------------------------------------------------
    
    _nod.pyx:63:17: 'SystemString' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class DiscBase:
        cdef unique_ptr[c_DiscBase] c_disc
    
        def get_data_partition(self) -> Optional[Partition]:
            cdef c_DiscBase.IPartition*partition = self.c_disc.get().getDataPartition()
                ^
    ------------------------------------------------------------
    
    _nod.pyx:77:13: 'IPartition' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def __init__(self, out_path: str, progress_callback: ProgressCallback):
            pass
    
        def __cinit__(self, out_path: str, progress_callback: ProgressCallback):
            cdef SystemString system_string = _str_to_system_string(out_path)
                ^
    ------------------------------------------------------------
    
    _nod.pyx:91:13: 'SystemString' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __dealloc__(self):
            del self.c_builder
    
        def build_from_directory(self, directory_in: str) -> None:
            def work():
                cdef SystemString system_string = _str_to_system_string(directory_in)
                    ^
    ------------------------------------------------------------
    
    _nod.pyx:100:17: 'SystemString' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            return _handleNativeException(work)
    
    
        @staticmethod
        def calculate_total_size_required(directory_in: str) -> Optional[int]:
            cdef SystemString system_string = _str_to_system_string(directory_in)
                ^
    ------------------------------------------------------------
    
    _nod.pyx:108:13: 'SystemString' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    def open_disc_from_image(path: str) -> Optional[Tuple[DiscBase, bool]]:
        def work():
            disc = DiscBase()
            cdef c_bool is_wii = True
    
            cdef SystemString system_string = _str_to_system_string(path)
                ^
    ------------------------------------------------------------
    
    _nod.pyx:119:13: 'SystemString' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        DiscBuilderGCN as c_DiscBuilderGCN, createFProgressFunction, EBuildResult,\
        EBuildResult_Success, EBuildResult_Failed, EBuildResult_DiskFull, string_to_system_string, \
        registerLogvisorToExceptionConverter, removeLogvisorToExceptionConverter, _handleNativeException, checkException
    
    cdef SystemString _str_to_system_string(str path):
        return string_to_system_string(path.encode("utf-8"))
              ^
    ------------------------------------------------------------
    
    _nod.pyx:19:11: 'string_to_system_string' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cdef void invoke_fprogress_function(object callback, float totalProg, const string& fileName, size_t fileBytesXfered) except *:
        callback(totalProg, fileName.decode("utf-8"), fileBytesXfered)
    
    @contextmanager
    def _log_exception_handler():
        registerLogvisorToExceptionConverter()
       ^
    ------------------------------------------------------------
    
    _nod.pyx:31:4: 'registerLogvisorToExceptionConverter' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    @contextmanager
    def _log_exception_handler():
        registerLogvisorToExceptionConverter()
        yield
        removeLogvisorToExceptionConverter()
       ^
    ------------------------------------------------------------
    
    _nod.pyx:33:4: 'removeLogvisorToExceptionConverter' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class ExtractionContext:
        cdef c_ExtractionContext c_context
    
        def __cinit__(self):
            self.c_context = c_ExtractionContext()
                            ^
    ------------------------------------------------------------
    
    _nod.pyx:39:25: 'c_ExtractionContext' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        @force.setter
        def force(self, value):
            self.c_context.force = value
    
        def set_progress_callback(self, callback):
            self.c_context.progressCB = createProgressCallbackFunction(callback, invoke_callback_function)
                                       ^
    ------------------------------------------------------------
    
    _nod.pyx:50:36: 'createProgressCallbackFunction' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        @force.setter
        def force(self, value):
            self.c_context.force = value
    
        def set_progress_callback(self, callback):
            self.c_context.progressCB = createProgressCallbackFunction(callback, invoke_callback_function)
                                                                                ^
    ------------------------------------------------------------
    
    _nod.pyx:50:77: Cannot convert 'void (object, const string &, float) except *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                        SystemStringView(system_string.c_str()),
                        context.c_context
                    )
                if not extraction_successful:
                    raise RuntimeError("Unable to extract")
            return _handleNativeException(work)
                  ^
    ------------------------------------------------------------
    
    _nod.pyx:71:15: '_handleNativeException' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def extract_to_directory(self, path: str, context: ExtractionContext) -> None:
            def work():
                cdef SystemString system_string = _str_to_system_string(path)
                with _log_exception_handler():
                    extraction_successful = self.c_partition.extractToDirectory(
                        SystemStringView(system_string.c_str()),
                       ^
    ------------------------------------------------------------
    
    _nod.pyx:66:20: 'SystemStringView' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class DiscBase:
        cdef unique_ptr[c_DiscBase] c_disc
    
        def get_data_partition(self) -> Optional[Partition]:
            cdef c_DiscBase.IPartition*partition = self.c_disc.get().getDataPartition()
                                                                 ^
    ------------------------------------------------------------
    
    _nod.pyx:77:62: Cannot convert '<error>' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __init__(self, out_path: str, progress_callback: ProgressCallback):
            pass
    
        def __cinit__(self, out_path: str, progress_callback: ProgressCallback):
            cdef SystemString system_string = _str_to_system_string(out_path)
            self.c_builder = new c_DiscBuilderGCN(SystemStringView(system_string.c_str()),
                                ^
    ------------------------------------------------------------
    
    _nod.pyx:92:29: 'c_DiscBuilderGCN' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __init__(self, out_path: str, progress_callback: ProgressCallback):
            pass
    
        def __cinit__(self, out_path: str, progress_callback: ProgressCallback):
            cdef SystemString system_string = _str_to_system_string(out_path)
            self.c_builder = new c_DiscBuilderGCN(SystemStringView(system_string.c_str()),
                                ^
    ------------------------------------------------------------
    
    _nod.pyx:92:29: new operator can only be applied to a C++ class
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __init__(self, out_path: str, progress_callback: ProgressCallback):
            pass
    
        def __cinit__(self, out_path: str, progress_callback: ProgressCallback):
            cdef SystemString system_string = _str_to_system_string(out_path)
            self.c_builder = new c_DiscBuilderGCN(SystemStringView(system_string.c_str()),
                                                 ^
    ------------------------------------------------------------
    
    _nod.pyx:92:46: 'SystemStringView' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            pass
    
        def __cinit__(self, out_path: str, progress_callback: ProgressCallback):
            cdef SystemString system_string = _str_to_system_string(out_path)
            self.c_builder = new c_DiscBuilderGCN(SystemStringView(system_string.c_str()),
                                                  createFProgressFunction(progress_callback, invoke_fprogress_function))
                                                 ^
    ------------------------------------------------------------
    
    _nod.pyx:93:46: 'createFProgressFunction' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            pass
    
        def __cinit__(self, out_path: str, progress_callback: ProgressCallback):
            cdef SystemString system_string = _str_to_system_string(out_path)
            self.c_builder = new c_DiscBuilderGCN(SystemStringView(system_string.c_str()),
                                                  createFProgressFunction(progress_callback, invoke_fprogress_function))
                                                                                            ^
    ------------------------------------------------------------
    
    _nod.pyx:93:89: Cannot convert 'void (object, float, const string &, size_t) except *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            cdef SystemString system_string = _str_to_system_string(out_path)
            self.c_builder = new c_DiscBuilderGCN(SystemStringView(system_string.c_str()),
                                                  createFProgressFunction(progress_callback, invoke_fprogress_function))
    
        def __dealloc__(self):
            del self.c_builder
                   ^
    ------------------------------------------------------------
    
    _nod.pyx:96:16: Deletion of non-Python, non-C++ object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def build_from_directory(self, directory_in: str) -> None:
            def work():
                cdef SystemString system_string = _str_to_system_string(directory_in)
                with _log_exception_handler():
                    self.c_builder.buildFromDirectory(SystemStringView(system_string.c_str()))
            return _handleNativeException(work)
                  ^
    ------------------------------------------------------------
    
    _nod.pyx:103:15: '_handleNativeException' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        def build_from_directory(self, directory_in: str) -> None:
            def work():
                cdef SystemString system_string = _str_to_system_string(directory_in)
                with _log_exception_handler():
                    self.c_builder.buildFromDirectory(SystemStringView(system_string.c_str()))
                                                     ^
    ------------------------------------------------------------
    
    _nod.pyx:102:50: 'SystemStringView' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    
        @staticmethod
        def calculate_total_size_required(directory_in: str) -> Optional[int]:
            cdef SystemString system_string = _str_to_system_string(directory_in)
            size = c_DiscBuilderGCN.CalculateTotalSizeRequired(SystemStringView(system_string.c_str()))
                                  ^
    ------------------------------------------------------------
    
    _nod.pyx:109:31: cimported module has no attribute 'CalculateTotalSizeRequired'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    
        @staticmethod
        def calculate_total_size_required(directory_in: str) -> Optional[int]:
            cdef SystemString system_string = _str_to_system_string(directory_in)
            size = c_DiscBuilderGCN.CalculateTotalSizeRequired(SystemStringView(system_string.c_str()))
                                  ^
    ------------------------------------------------------------
    
    _nod.pyx:109:31: Compiler crash in AnalyseExpressionsTransform
    
    ModuleNode.body = StatListNode(_nod.pyx:1:0)
    StatListNode.stats[16] = StatListNode(_nod.pyx:84:5)
    StatListNode.stats[0] = CClassDefNode(_nod.pyx:84:5,
        as_name = 'DiscBuilderGCN',
        class_name = 'DiscBuilderGCN',
        module_name = '',
        visibility = 'private')
    CClassDefNode.body = StatListNode(_nod.pyx:85:4)
    StatListNode.stats[4] = CompilerDirectivesNode(_nod.pyx:107:4)
    CompilerDirectivesNode.body = StatListNode(_nod.pyx:107:4)
    StatListNode.stats[0] = DefNode(_nod.pyx:107:4,
        is_staticmethod = True,
        modifiers = [...]/0,
        name = 'calculate_total_size_required',
        np_args_idx = [...]/0,
        num_required_args = 1,
        outer_attrs = [...]/2,
        py_wrapper_required = True,
        reqd_kw_flags_cname = '0',
        self_in_stararg = True,
        used = True)
    File 'ExprNodes.py', line 5338, in infer_type: SimpleCallNode(_nod.pyx:109:58,
        result_is_used = True,
        use_managed_ref = True)
    File 'ExprNodes.py', line 6826, in infer_type: AttributeNode(_nod.pyx:109:31,
        attribute = 'CalculateTotalSizeRequired',
        is_attribute = 1,
        needs_none_check = True,
        result_is_used = True,
        use_managed_ref = True)
    
    Compiler crash traceback from this point on:
      File "/usr/lib/python3.7/site-packages/Cython/Compiler/ExprNodes.py", line 6826, in infer_type
        return node.entry.type
    AttributeError: 'NoneType' object has no attribute 'type'
    Compiling /tmp/pip-install-vyt09y6o/nod/_nod.pyx because it depends on /usr/lib/python3.7/site-packages/Cython/Includes/libcpp/string.pxd.
    [1/1] Cythonizing /tmp/pip-install-vyt09y6o/nod/_nod.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vyt09y6o/nod/setup.py", line 144, in <module>
        create_extension=create_extension,
      File "/usr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
        cythonize_one(*args)
      File "/usr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: /tmp/pip-install-vyt09y6o/nod/_nod.pyx
    
    ----------------------------------------
```

**Comment by SpaghettiToastBook** [comment]
It installs if I do so from this repository, so this may be due to something wrong in the PyPI package.

**Comment by henriquegemignani** [comment]
This repository has submodules. Maybe I broke something on the source package? :(

The recommended way anyway is to use the binary wheels. There are manylinux2010 wheels for Python 3.5, 3.6 and 3.7. Maybe you should update your pip so you can install then?

**Comment by SpaghettiToastBook** [comment]
I just tried to install from PyPI again and it worked just fine, so I guess whatever the problem was is gone.
